on:
  release:
    types: [published]

jobs:
  notify-release:
    name: "Notify Release"
    runs-on: ubuntu-latest
    if: github.event.sender.login != 'dependabot[bot]' && github.event_name == 'release'
    steps:
      - name: Send release notification to Discord
        uses: SethCohen/github-releases-to-discord@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          avatar_url: https://avatars.githubusercontent.com/u/49069598?v=4&size=64
          username: Hytale Server Release Bot
          content: "@everyone New release: ${{ github.event.release.name }} (v${{ github.event.release.tag_name }})\n\nChangelog: ${{ github.event.release.html_url }}"
          reduce_headings: true